FROM amazoncorretto:17.0.9-al2023

COPY ./target/fss-hockey-spring-${project.version}.jar ./fss-hockey-spring.jar

CMD ["sh", "-c", "java -version"]
CMD ["sh", "-c", "java -jar fss-hockey-spring.jar"]
